pagehelper:
  helper-dialect: mysql               # 指定mysql数据库
  reasonable: true                    # 参数合理化
  support-methods-arguments: true     # 支持通过Mapper接口参数来传递分页参数
  params: countSql                    # 为了支持startPage方法，配置参数映射